export { default as App } from './App/App';
export { default as ScrollToTop } from './ScrollToTop/ScrollToTop';
export { default as Pages } from './Pages/Pages';
export { default as Navigation } from './Navigation/Navigation';
export { default as Home } from './Home/Home';
export { default as About } from './About/About';
export { default as Portfolio } from './Portfolio/Portfolio';
export { default as Logo } from './Logo/Logo';
export { default as Linkedin } from './Social/Linkedin';
export { default as Github} from './Social/Github';
export { default as Medium} from './Social/Medium';
export { default as Gmail} from './Social/Gmail';
export { default as Javascript} from './Tech/Javascript';
export { default as Html} from './Tech/Html';
export { default as Css} from './Tech/Css';
export { default as Node} from './Tech/Node';
export { default as Mongodb} from './Tech/Mongodb';
export { default as Jquery} from './Tech/Jquery';
export { default as ReactIcon} from './Tech/React';
export { default as Heroku} from './Tech/Heroku';
export { default as GithubPages} from './Tech/GithubPages';