export { default as Pages } from './Pages/Pages';
export { default as Navigation } from './Navigation/Navigation';
export { default as App } from './App/App';
export { default as Home } from './Home/Home';
export { default as Matrix } from './Matrix/Matrix';
export { default as About } from './About/About';
export { default as Portfolio } from './Portfolio/Portfolio';
export { default as Logo } from './Logo/Logo';
export { default as Linkedin } from './Social/Linkedin';
export { default as Github} from './Social/Github';
export { default as Medium} from './Social/Medium';
export { default as Gmail} from './Social/Gmail';
export { default as Javascript} from './Tech/Javascript';
export { default as Html} from './Tech/Html';
export { default as Css} from './Tech/Css';
export { default as Node} from './Tech/Node';